name: Test action

on: [push,pull_request,workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Prepare zephyr dependencies
        run: |
            python -m pip install --upgrade pip
            pip install west
      - name: Prepare zephyr codebase
        run: ./prepare_zephyr.sh
        shell: bash
      - name: Install zephyr build dependencies
        run: |
            pip install -r zephyr/scripts/requirements.txt
      - name: Build zephyr sample binaries
        run: ./build_binaries.sh
        shell: bash
      - name: Run tests
        uses: antmicro/renode-test-action@v1.0.0
        with:
          renode-version: 'latest'
          tests-to-run: 'nrf52840.robot'
      - name: Archive results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            report.html
            log.html
            robot_output.xml
      - name: Output sample binaries
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            artifacts/zephyr-hello_world.elf
            artifacts/zephyr-shell_module.elf
